=== Bertrand82/cvGenerator/CvGenerator/src/main/ressources/xsd/cv.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
	elementFormDefault="qualified" attributeFormDefault="unqualified">
	<!-- XML Schema Generated from XML Document on Mon Jan 25 2021 13:01:51 
		GMT+0100 (heure normale dâ€™Europe centrale) -->
	<!-- with XmlGrid.net Free Online Service http://xmlgrid.net -->
	<xs:element name="cv">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="title" type="xs:string"></xs:element>
				<xs:element name="etatCivil">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="name" type="xs:string"></xs:element>
							<xs:element name="first-name" type="xs:string"></xs:element>
							<xs:element name="date-of-birth" type="xs:string" minOccurs="0" maxOccurs="1"></xs:element>
							<xs:element name="photo-path" minOccurs="0" maxOccurs="1"></xs:element>
							<xs:element name="telephon" type="xs:string"></xs:element>
							<xs:element name="email" type="xs:string"></xs:element>

							<xs:element name="address">
								<xs:complexType>
									<xs:sequence>
										<xs:element name="ligne1" type="xs:string"></xs:element>
										<xs:element name="ligne2" type="xs:string" minOccurs="0" maxOccurs="1"></xs:element>
										<xs:element name="city" type="xs:string"></xs:element>
										<xs:element name="zipCode" type="xs:int"></xs:element>
										<xs:element name="country" type="xs:string"></xs:element>
									</xs:sequence>
								</xs:complexType>
							</xs:element>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
				<xs:element name="educations">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="education" maxOccurs="unbounded">
								<xs:complexType>
									<xs:sequence>
										<xs:element name="diploma" type="xs:string"></xs:element>
										<xs:element name="school" type="xs:string"></xs:element>
										<xs:element name="year" type="xs:int"></xs:element>
									</xs:sequence>
								</xs:complexType>
							</xs:element>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
				<xs:element name="languages">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="language" maxOccurs="unbounded">
								<xs:complexType>
									<xs:sequence>
										<xs:element name="languageName" type="xs:string"></xs:element>
										<xs:element name="languageLevel" type="xs:string"></xs:element>
									</xs:sequence>
								</xs:complexType>
							</xs:element>
						</xs:sequence>
					</xs:complexType>
				</xs:element>

				<xs:element maxOccurs="unbounded" name="skills">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="skillLabel" type="xs:string" />
							<xs:element maxOccurs="unbounded" name="skill">
								<xs:complexType>
									<xs:simpleContent>
										<xs:extension base="xs:string">
											<xs:attribute name="nivel"
												type="xs:unsignedByte" use="required" />
										</xs:extension>
									</xs:simpleContent>
								</xs:complexType>
							</xs:element>
						</xs:sequence>
					</xs:complexType>
				</xs:element>

				<xs:element name="experiences">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="experience" maxOccurs="unbounded">
								<xs:complexType>
									<xs:all>
										<xs:element name="experienceTitle" type="xs:string"></xs:element>
										<xs:element name="dateStart" type="xs:string"></xs:element>
										<xs:element name="dateEnd" type="xs:string"></xs:element>
										<xs:element name="typeOfContract" type="xs:string"
											nillable="true"></xs:element>
										<xs:element name="location">
											<xs:complexType>
												<xs:sequence>
													<xs:element name="city" type="xs:string"></xs:element>
													<xs:element name="country" type="xs:string"></xs:element>
												</xs:sequence>
											</xs:complexType>
										</xs:element>
										<xs:element name="company">
											<xs:complexType>
												<xs:sequence>
													<xs:element name="companyName" type="xs:string"></xs:element>
													<xs:element name="companyInfos" type="xs:string"></xs:element>
												</xs:sequence>
											</xs:complexType>
										</xs:element>
										<xs:element name="context" type="xs:string"></xs:element>
										<xs:element name="myGoal" type="xs:string"></xs:element>
										<xs:element name="tasks">
											<xs:complexType>
												<xs:sequence maxOccurs="unbounded">
													<xs:element name="task" type="xs:string">
													</xs:element>
												</xs:sequence>
											</xs:complexType>
										</xs:element>
										<xs:element name="technos" type="xs:string"></xs:element>
									</xs:all>
								</xs:complexType>
							</xs:element>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== Bertrand82/cvGenerator/JavaCvGenerator/src/main/java/bg/cv/generator/cv_short.xml
<?xml version="1.0" encoding="UTF-8"?>
<cv xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:noNamespaceSchemaLocation="src/main/ressources/xsd/cv.xsd">
	<title>Expert Java et J2EE</title>
	<etatCivil>
		<name>Guiral</name>
		<first-name>Bertrand</first-name>
		<date-of-birth>26/08/1958 </date-of-birth>
		<photo-path>images/bertrand.jpg</photo-path>
		<telephon>0682426361</telephon>
		<email>bertrand.guiral@gmail.com</email>

		<address>
			<ligne1>2 rue Cariben</ligne1>
			<ligne2></ligne2>
			<city>Montpezat de Quercy</city>
			<zipCode>82270</zipCode>
			<country>France</country>
		</address>
	</etatCivil>
</cv>
